#!/bin/bash
 
set -e

BRANCH=gh-pages
DIR=target/demo/

git branch -D $BRANCH || echo 'skip'

rm -rf $DIR

clojure -M:cljs:shadow-cljs release demo

bb -cp src -m portal.runtime.index > $DIR/index.html

deploy() {
  git --git-dir=.git --work-tree="$DIR" "$@"
}

deploy checkout --orphan $BRANCH
deploy add .
deploy commit -m 'Build demo'
deploy checkout master -f

rm -rf $DIR

