name: Deploy PWA

on:
  push:
    branches: [ master ]

jobs:
  app:
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/setup
    - run: bb app
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/pwa-release/
